### ISSUE TITLE
cmd key belong MAC book, how to active on other keyboard of linux?

### ISSUE THREAD

**Issue by gotope** [robinsloan/rnn-writer#4]
I 'm using a normal PC not MAC system, there is no cmd key, 
possible change the the keymap in the rnn-writer？ 

"shift-alt-R": "rnn-writer:toggle"

**Comment by robinsloan** [comment]
Hi @gotope: you can edit the file `keymaps/rnn-writer.cson` and change the shortcut to whatever you'd like! Just be sure to reload the plugin: View > Developer > Reload Window. (Or close Atom and open it again.)

**Comment by gotope** [comment]
@robinsloan  thanks, it works, looks quite cool.
