### ISSUE TITLE
apm in my command line

### ISSUE THREAD

**Issue by erikvanmechelen** [robinsloan/rnn-writer#7]
Here's the result when attempting command line...apm command not found: 

Eriks-MBP:rnn-writer erikvanmechelen$ git clone https://github.com/robinsloan/rnn-writer.git
Cloning into 'rnn-writer'...
remote: Counting objects: 53, done.
remote: Total 53 (delta 0), reused 0 (delta 0), pack-reused 53
Unpacking objects: 100% (53/53), done.
Eriks-MBP:rnn-writer erikvanmechelen$ cd rnn-writer
Eriks-MBP:rnn-writer erikvanmechelen$ apm install
-bash: apm: command not found
Eriks-MBP:rnn-writer erikvanmechelen$

**Comment by robinsloan** [comment]
Hey @erikvanmechelen: in Atom, use the `Atom > Install Shell Commands` menu item, close and reopen your terminal program, and try again. Let me know if it still doesn't work…!

**Comment by erikvanmechelen** [comment]
This worked! Now all I need is the highly suspicious api key ... 👍
